# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    ## H2
    url: jdbc:h2:mem:mydb

    
  h2:
    console:
      enabled: true



  jpa:
    hibernate:
      ddl-auto: create
     


jwt:
  header: Authorization
  secret: tasksSecret
  expiration: 6048003242423
  route:
    authentication:
      path: auth
      refresh: refresh
      

#logging:
#  level:
#    org.springframework:
#      security: DEBUG
